name: Lint

on: [push, pull_request]

jobs:
  shellcheck:
    name: Shell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cp example.env .env
      - name: Check Shell Files
        uses: pataraco/shellcheck-action@v0.1.0
